# Site Settings
title: Your Cybersecurity Portfolio
description: A vibrant showcase of my cybersecurity projects, skills, and achievements.

## Build Settings
theme: jekyll-theme-cayman # Choose a theme for your GitHub Pages site
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
plugins:
  - jekyll-seo-tag
  - jekyll-feed

## Permalinks
permalink: /:title/

## Navigation Links
header_pages:
  - Home: /
  - Projects: /projects
  - Blog: /blog
  - Contact: /contact

## SEO
seo:
  name: Your Name
  social:
    - title: LinkedIn
      url: https://www.linkedin.com/in/your-profile
    - title: Twitter
      url: https://twitter.com/your-profile

## Analytics (Optional)
google_analytics: UA-XXXXXXXXX-X # Your Google Analytics Tracking ID

## GitHub Repository
repository:
  url: https://github.com/your-username/your-repo

## Footer
footer:
  links:
    - title: Privacy Policy
      url: /privacy-policy
    - title: Terms of Service
      url: /terms-of-service
    - title: Accessibility Statement
      url: /accessibility-statement

## Customization Options
logo: /assets/images/logo.png # Path to your logo image
favicon: /assets/images/favicon.ico # Path to your favicon

## Styling Options
style:
  colors:
    primary: "#007bff" # Change to your preferred primary color
    secondary: "#6c757d" # Change to your preferred secondary color
    background: "#f8f9fa" # Change to your preferred background color
    text: "#343a40" # Change to your preferred text color
  fonts:
    heading: Arial, sans-serif # Change to your preferred font for headings
    body: Roboto, sans-serif # Change to your preferred font for body text
